# Generated by Django 4.0.5 on 2022-07-01 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "brand",
                    models.CharField(
                        help_text="Марка автомобиля",
                        max_length=64,
                        verbose_name="марка",
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        help_text="Модель автомобиля",
                        max_length=128,
                        verbose_name="модель",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        help_text="Цвет автомобиля", max_length=64, verbose_name="цвет"
                    ),
                ),
                (
                    "registration_number",
                    models.CharField(
                        help_text="Регистрационный номер автомобиля",
                        max_length=16,
                        verbose_name="регистрационный номер",
                    ),
                ),
                (
                    "year_of_manufacture",
                    models.PositiveIntegerField(
                        help_text="Год выпуска автомобиля", verbose_name="год выпуска"
                    ),
                ),
                (
                    "vin",
                    models.CharField(
                        help_text="Идентификационный номер транспортного средства",
                        max_length=17,
                        unique=True,
                        verbose_name="VIN",
                    ),
                ),
                (
                    "vehicle_registration_number",
                    models.CharField(
                        help_text="Номер СТС (свидетельства о регистрации",
                        max_length=20,
                        verbose_name="номер СТС",
                    ),
                ),
                (
                    "vehicle_registration_date",
                    models.DateField(
                        help_text="Дата СТС (свидетельства о регистрации",
                        verbose_name="дата СТС",
                    ),
                ),
            ],
            options={
                "verbose_name": "транспортное средство",
                "verbose_name_plural": "транспортные средства",
            },
        ),
    ]
