# Generated by Django 4.0.5 on 2022-07-02 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_vehicle_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ['id'], 'verbose_name': 'транспортное средство', 'verbose_name_plural': 'транспортные средства'},
        ),
    ]
