# Generated by Django 4.0.5 on 2022-07-02 22:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_vehicle_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vin',
            field=models.CharField(help_text='Идентификационный номер транспортного средства', max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message='VIN должен иметь 17 символов, допустимы цифры и большие латинские буквы, кроме I, O, Q', regex='^[0-9A-HJ-NPR-Z]{17}$')], verbose_name='VIN'),
        ),
    ]
